server:
  port: 8081
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        person-in:
          destination: person
          contentType: application/json
          group: consumer
